version: '3.8'

services:

  nats-server:
    image: nats:latest
    ports:
      # - "4222:4222"
      # - "6222:6222"
      - "8222:8222"
    restart: always
    networks:
      - microservices-network
  
  

  client-gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:5000
    environment:
      - NODE_ENV=development
      - PORT=5000
      - NATS_SERVERS=${NATS_SERVERS}
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    restart: always
    command: pnpm run start:dev
    networks:
      - microservices-network

  products-service:
    build: ./products
    ports:
      - "4100:4100"
    volumes:
      - ./products/src:/usr/src/app/src
      - ./products/prisma:/usr/src/app/prisma
    command: pnpm run start:dev
    environment:
      - NODE_ENV=development
      - PORT=4100
      - HOST=127.0.0.1
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=file:./dev.db
    restart: always
    networks:
      - microservices-network


  orders-service:
    depends_on:
      - orders-db
    build: ./orders
    volumes:
      - ./orders/src:/usr/src/app/src
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
      - PORT=4200
      - HOST=127.0.0.1
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=postgresql://postgres:test1234@orders-db:5432/ordersdb
    restart: always
    command: pnpm run start:dev
    networks:
      - microservices-network
  
  auth-service:
    build: ./auth
    depends_on:
      - localstack
    volumes:
      - ./auth/src:/usr/src/app/src
    ports:
      - "4600:4600"
    environment:
      - NODE_ENV=development
      - PORT=4600
      - HOST=127.0.0.1
      - NATS_SERVERS=${NATS_SERVERS}
      - AUTH_URL=${AUTH_URL}
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DYNAMODB_ENDPOINT=http://localstack:4566
    restart: always
    command: pnpm run start:dev
    networks:
      - microservices-network

  orders-db:
    container_name: orders-database
    image: postgres:16.2
    restart: always
    volumes:
      - ./orders/postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=ordersdb
    networks:
      - microservices-network

  payments-service:
    build: ./payments
    volumes:
      - ./payments/src:/usr/src/app/src
    ports:
      - ${PAYMENTS_PORT}:${PAYMENTS_PORT}
    environment:
      - PORT=${PAYMENTS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_API_KEY_SECRET=${STRIPE_API_KEY_SECRET}
      - STRIPE_WEBHOOK_SIGNING_SECRET=${STRIPE_WEBHOOK_SIGNING_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
    restart: always
    command: pnpm run start:dev
    networks:
      - microservices-network

  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3,sqs,ses,secretsmanager,events,ssm,dynamodb
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "4566:4566"  # endpoint principal de LocalStack (todas las APIs AWS)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
    volumes:
      - ./scripts:/etc/localstack/init/ready.d
    networks:
      - microservices-network

  sqs-admin:
    image: pacovk/sqs-admin:latest
    depends_on:
      - localstack
    environment:
      - SQS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - SQS_AWS_REGION=us-east-1
    ports:
      - "3999:3999"  # UI para manipular colas (en http://localhost:3999)
    networks:
      - microservices-network

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:5.1.3
    depends_on:
      - localstack
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "8001:8001"  # UI para visualizar tablas DynamoDB (en http://localhost:8001)
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge